export const REGISTER = "REGISTER";
export const OPEN_ACC = "OPEN_ACC";
export const LOG_OUT = "LOG_OUT";
export const CREATE_SERVER = "CREATE_SERVER";
export const RETREIVE_SERVER_AS_LEADER = 'RETREIVE_SERVER_AS_LEADER';
export const GET_SERVER_CHANNELS = 'GET_SERVER_CHANNELS';